### ISSUE TITLE
Page bugs for ol and ul

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo-dev-portal#104]
https://developers.neo.org/docs/n3/node/cli/setup There is an error in the markdown to web page conversion. 1. 2. 3. in the source file are missing after conversion to web. @apisit 

<img width="1129" alt="8f3c8476038cbecc6166e2f7234aadd" src="https://github.com/neo-project/neo-dev-portal/assets/6295602/e925afe8-f1fe-4b1e-9e78-2425166c59a5">

<img width="1140" alt="image" src="https://github.com/neo-project/neo-dev-portal/assets/6295602/e1738603-68b2-4308-bb98-059c439c7dd6">

**Comment by apisit** [comment]
Thanks for reporting. 
Fixed in the latest release.
