### ISSUE TITLE
Suggest adding code highlighting

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo-dev-portal#58]
Suggest adding code highlighting

Such as

GitHub:
<img width="481" alt="image" src="https://user-images.githubusercontent.com/6295602/220807853-d3f868fd-c96d-4c6a-b760-16ac18d296a0.png">

docs.neo.org:
<img width="552" alt="image" src="https://user-images.githubusercontent.com/6295602/220807765-fa0ed51b-a97e-4224-b35c-30da2beb1ac5.png">
<img width="535" alt="image" src="https://user-images.githubusercontent.com/6295602/220807928-a3ff858a-5658-4b76-bce4-b807039b3ea9.png">

**Comment by chenzhitong** [comment]
https://docusaurus.io/docs/markdown-features/code-blocks#supported-languages

**Comment by chenzhitong** [comment]
change the `c#` to `cs`


https://github.com/neo-project/neo-dev-portal/blob/645418f9fcd07a791b472dbad9519fabd8d61e6b/docs/n3/develop/write/basics.md?plain=1#L7-L16

**Comment by apisit** [comment]
Thanks for spotting this. Updated. It will be in the next release.
