### ISSUE TITLE
Suggest changing the syntax of the quote to standard markdown syntax

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo-dev-portal#59]
Suggest changing the syntax of the quote to standard markdown syntax

**from**

:::caution

Do not open or create a wallet on an insecure computer. Once the wallet file or wallet password is lost, it will cause the loss of your assets. So back up your wallet file securely, keep it safe, and remember your wallet password. :::

**to**

> [!CAUTION]
>
> Do not open or create a wallet on an insecure computer. Once the wallet file or wallet password is lost, it will cause the loss of your assets. So back up your wallet file securely, keep it safe, and remember your wallet password.

This makes for a good reading experience on GitHub as well

**Comment by apisit** [comment]
Unfortunately, this is what Docusaurus provides as default. 
https://docusaurus.io/docs/next/markdown-features/admonitions

I can try adding to support both.
