### ISSUE TITLE
CSS: missing margins between some elements

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo-dev-portal#60]
![image](https://user-images.githubusercontent.com/6295602/220813497-db2d3a87-895b-4f97-8ec5-36f160ad31c0.png)

![image](https://user-images.githubusercontent.com/6295602/220813503-c6795331-63cc-4ba3-a524-d0029b594112.png)

![image](https://user-images.githubusercontent.com/6295602/220813507-444363b9-bde4-4e63-bc1c-da9e12eebcb2.png)

**Comment by apisit** [comment]
Updated.
