### ISSUE TITLE
Instructions Fee is outdated

### ISSUE THREAD

**Issue by luc10921** [neo-project/neo-dev-portal#63]
The cost of the Opcodes is outdated on the [Instruction Fee](https://developers.neo.org/docs/n3/fees#instruction-fee) page and the reference links are outdated too. Probably because the [neo-project renamed a folder](https://github.com/neo-project/neo/pull/2790).
The table with the [correct prices ](https://github.com/neo-project/neo/blob/master/src/Neo/SmartContract/ApplicationEngine.OpCodePrices.cs)should be:

| Fee（GAS） | OpCode                                                       |
| ---------- | ------------------------------------------------------------ |
| 0.00032768 | CALLT                                                        |
| 0.00008192 | VALUES, APPEND, SETITEM, REVERSEITEMS, CONVERT                        |
| 0.00004096 | PUSHDATA4                                                    |
| 0.00002048 | MEMCPY, CAT, SUBSTR, LEFT, RIGHT, MODPOW, PACKMAP, PACKSTRUCT, PACK, UNPACK                    |
| 0.00000512 | PUSHDATA2, CALL, CALL_L, CALLA, THROW, NEWARRAY, NEWARRAY_T, NEWSTRUCT |
| 0.00000256 | NEWBUFFER                                                    |
| 0.00000064 | INITSLOT, POW, SQRT, HASKEY, PICKITEM                                     |
| 0.00000032 | EQUAL, NOTEQUAL, MODMUL                                               |
| 0.00000016 | XDROP, CLEAR, ROLL, REVERSEN, INITSSLOT, NEWARRAY0, NEWSTRUCT0, KEYS, REMOVE, CLEARITEMS, POPITEM |
| 0.00000008 | PUSHDATA1, AND, OR, XOR, ADD, SUB, MUL, DIV, MOD, SHL, SHR, BOOLAND, BOOLOR, NUMEQUAL, NUMNOTEQUAL, LT, LE, GT, GE, MIN, MAX, WITHIN, NEWMAP |
| 0.00000004 | PUSHINT128, PUSHINT256, PUSHA, TRY, TRY_L, ENDTRY, ENDTRY_L, ENDFINALLY, INVERT, SIGN, ABS, NEGATE, INC, DEC, NOT, NZ, SIZE |
| 0.00000002 | JMP, JMP_L, JMPIF, JMPIF_L, JMPIFNOT, JMPIFNOT_L, JMPEQ, JMPEQ_L, JMPNE, JMPNE_L, JMPGT, JMPGT_L, JMPGE, JMPGE_L, JMPLT, JMPLT_L, JMPLE, JMPLE_L, DEPTH, DROP, NIP, DUP, OVER, PICK, TUCK, SWAP, ROT, REVERSE3, REVERSE4, LDSFLD0, LDSFLD1, LDSFLD2, LDSFLD3, LDSFLD4, LDSFLD5, LDSFLD6, LDSFLD, STSFLD0, STSFLD1, STSFLD2, STSFLD3, STSFLD4, STSFLD5, STSFLD6, STSFLD, LDLOC0, LDLOC1, LDLOC2, LDLOC3, LDLOC4, LDLOC5, LDLOC6, LDLOC, STLOC0, STLOC1, STLOC2, STLOC3, STLOC4, STLOC5, STLOC6, STLOC, LDARG0, LDARG1, LDARG2, LDARG3, LDARG4, LDARG5, LDARG6, LDARG, STARG0, STARG1, STARG2, STARG3, STARG4, STARG5, STARG6, STARG, ISNULL, ISTYPE |
| 0.00000001 | PUSHINT8, PUSHINT16, PUSHINT32, PUSHINT64, PUSHT, PUSHF, PUSHNULL, PUSHM1, PUSH0, PUSH1, PUSH2, PUSH3, PUSH4, PUSH5, PUSH6, PUSH7, PUSH8, PUSH9, PUSH10, PUSH11, PUSH12, PUSH13, PUSH14, PUSH15, PUSH16, NOP, ASSERT |
| 0          | ABORT, RET, SYSCALL

**Comment by apisit** [comment]
@Celia18305 @steven1227  Can you help verify this?
